#pragma once
#include <cstdint>
#include <cassert>
#include <cstddef>
#include <ctime>
#include <cmath>
#include <cstring>
#include <memory>
#include <string>
#include <string_view>
#include <array>
#include <vector>
#include <map>
#include <unordered_map>
#include <thread>
#include <chrono>
#include <tuple>
#include <span>
#include <type_traits>
#include <optional>
#include <AL/al.h>
#include <AL/alc.h>
#include <gainput/gainput.h>